// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AT01UdanarejestracjauytkownikaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void aT01Udanarejestracjauytkownika() {
    driver.get("http://localhost:8080/accounts/controller?action=db_reset");
    driver.findElement(By.linkText("Register")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("asd");
    driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2)")).click();
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("asd");
    driver.findElement(By.name("repeat_password")).click();
    driver.findElement(By.name("repeat_password")).sendKeys("asd");
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("asd");
    driver.findElement(By.name("addressData")).click();
    driver.findElement(By.name("addressData")).sendKeys("asd");
    driver.findElement(By.name("submit")).click();
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("asd");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("asd");
    driver.findElement(By.name("submit")).click();
    driver.findElement(By.name("submitAdd")).click();
    driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(1)")).click();
    vars.put("account_number", driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(1)")).getText());
    driver.findElement(By.name("accountDeposit")).click();
    {
      WebElement dropdown = driver.findElement(By.name("accountDeposit"));
      dropdown.findElement(By.xpath("//option[. = 'vars.get("account_number").toString()']")).click();
    }
    driver.findElement(By.name("accountPayUp")).click();
    {
      WebElement dropdown = driver.findElement(By.name("accountPayUp"));
      dropdown.findElement(By.xpath("//option[. = 'vars.get("account_number").toString()']")).click();
    }
    driver.findElement(By.name("amountPayUp")).click();
    driver.findElement(By.name("amountDeposit")).click();
    driver.findElement(By.name("amountDeposit")).sendKeys("100");
    driver.findElement(By.name("submitDeposit")).click();
    driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(3)")).click();
    driver.findElement(By.name("accountPayUp")).click();
    {
      WebElement dropdown = driver.findElement(By.name("accountPayUp"));
      dropdown.findElement(By.xpath("//option[. = 'vars.get("account_number").toString()']")).click();
    }
    driver.findElement(By.name("amountPayUp")).click();
    driver.findElement(By.name("amountPayUp")).sendKeys("1");
    driver.findElement(By.name("submitPayUp")).click();
    driver.findElement(By.cssSelector("#accounts tr:nth-child(2)")).click();
    driver.close();
  }
}
